#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01). Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.
# Info dig command: https://linube.com/ayuda/articulo/287/como-utilizar-el-comando-dig#:~:text=Dig%20es%20un%20comando%20que,y%20tambi%C3%A9n%20desde%20Mac%20OS.
# Info awk command: https://geekland.eu/uso-del-comando-awk-en-linux-y-unix-con-ejemplos/
# Info Operators in Bash: https://linuxize.com/post/bash-if-else-statement/
# Info functions in bash: https://tldp.org/LDP/abs/html/complexfunct.html

print_rec ()
{
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]; then
   for subs in "www" "lb-01" "web-01" "web-02"
   do
       print_rec "$1" "$subs"
   done
else
    print_rec "$1" "$2"
fi
