#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# "lt" is less than - le indicamos que si es menor a cuatro los comandos en linea que se imprima el mensaje de "usage"
# Con el "$#" nos devuelve el largo de los comandos en linea que se pasaron
# Con el signo de pesos se accede a los comandos que se pasaron en linea

if [ "$#" -lt 4 ]
    then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3@$2":~/
fi
