#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo apt update
sudo apt-get -y install nginx 
cd /var/www/html
sudo chmod 777 index.nginx-debian.html
echo Hello World! > index.nginx-debian.html
sudo service nginx restart
