#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
# Requirements:
# * Install nginx on your web-01 server
# * Nginx should be listening on port 80 - por default las http request se escuchan en el puerto 80
# * When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World
# * As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# * You can’t use systemctl for restarting nginx
# Lo primero que se hace es correr el comando: sudo apt update para que se actualice todo lo que se tenga que actualizar.
# Luego ponemos el comanod para instalar el web server "nginx".
# Nos movemos con "cd" a la ruta var/www/html que es donde se encuentra el archivo "index.nginx-debian.html" el cual vamos a modificar
# para que apraezca "Hello World!" al entrar a nuestro sitio web (el cual estamos creando con nginx) con la IP de nuestro servidor.
# Por ultimo usamos el comando: "sudo service nginx restart" para asegurarnos que se hicieron los cambios que indicamos en el script.

sudo apt update
sudo apt-get -y install nginx 
cd /var/www/html || exit
sudo chmod 777 index.nginx-debian.html
echo Hello World! > index.nginx-debian.html
sudo service nginx restart
