#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
# Use ps with flags to show the info in the way they tell us in the task
# Info for the flags for the commnad 'ps': https://man7.org/linux/man-pages/man1/ps.1.html

ps auxf
