#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process - but without using commann kill or killall
# pkill command --> https://linuxize.com/post/pkill-command-in-linux/

pkill -f 4-to_infinity_and_beyond
