#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 (Fizz Buzz)

# Declare iter variable
n=1

while ((n<=100))
do
	if ((n%3 == 0 && n%5 == 0))
	then
		echo "FizzBuzz"
	elif ((n%3 == 0))
	then
		echo "Fizz"
	elif ((n%5 == 0))
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	((n++))
done
