#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

etc_passwd_file="/etc/passwd"

while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "$etc_passwd_file"
