#!/usr/bin/env bash
# This script is displaying 12 hours and the 59 minutes of each hour

hours=0
minutes=1

while ((hours<=12))
do
	echo "Hour: "$hours
	minutes=1
	while ((minutes<=59))
	do
		echo "$minutes"
	((minutes++))
	done
((hours++))
done
