#!/usr/bin/env bash
# In this first debugging project, you will need to get Apache to run on the container and
# to return a page containing Hello Holberton when querying the root of it.
# Info restart --> https://www.cyberciti.biz/faq/star-stop-restart-apache2-webserver/

sudo service apache2 restart
