#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# Info sobre la flag -i: https://linuxcommand.org/lc3_man_pages/ssh1.html
# How to connect to a server: https://www.digitalocean.com/community/tutorials/ssh-essentials-working-with-ssh-servers-clients-and-keys#connecting-to-a-remote-server

ssh -i ~/.ssh/school ubuntu@54.160.237.107
